http:
  routers:
    n8n:
      rule: "Host(`n8n.mountainclub.co.nz`)"
      service: n8n
      entryPoints:
        - web
        - websecure
  
  services:
    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"