http:
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
  routers:
    n8n:
      rule: "Host(`n8n.mountainclub.co.nz`)"
      service: n8n
      entryPoints:
        - web
        - websecure
  
  services:
    n8n:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: "https://n8n-8i971c.sliplane.app"