api:
  dashboard: true
  insecure: true  # In production, consider using authMiddleware to secure this

entryPoints:
  web:
    address: ":80"
    # Optional: redirect HTTP to HTTPS
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  websecure:
    address: ":443"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-net
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Optional: Access logs
accessLog:
  filePath: "/data/access.log"

# Optional: Logs configuration
log:
  filePath: "/data/traefik.log"
  level: INFO